### PR TITLE
[IMP] improvment v12 added constrain when book request time  card det…

### PR DESCRIPTION
**Pull request by nisarg-serpentcs**
improvement v12 added constrain when book request time card details duration checked.

### CODE REVIEW

**Comment by AnuKPatel** [comment]
Please review thie code again

**Comment by nisarg-serpentcs** [comment]
changed method of check_book_issue.

**Comment by nisarg-serpentcs** [comment]
changed condition for check_book_issue method.

**Comment by AnuKPatel** [comment]
There is another method having same check in it while issue the book.
Please check that method and add improvements

**Pull request merged**
