### PR TITLE
improve evalution module rating fields v12

### PR DESCRIPTION
**Pull request by nisarg-serpentcs**
improve evaluation module rating fields v12

### CODE REVIEW

**Comment by AnuKPatel** [comment]
You need to do changes in demo data as well.

**Comment by nisarg-serpentcs** [comment]
changed demo data

**Comment by nisarg-serpentcs** [comment]
changed demo data from school evaluation module.

**Comment by nisarg-serpentcs** [comment]
Improve demo data id changed.

**Pull request merged**
